parameters:
    db_user: "%env(MYSQL_ENV_DB_USER)%"
    db_pass: "%env(MYSQL_ENV_MYSQL_ROOT_PASSWORD)%"
    db_host: "%env(SIMPLE_SHOP_MYSQL_PORT_3306_TCP_ADDR)%"
    db_port: "%env(SIMPLE_SHOP_MYSQL_PORT_3306_TCP_PORT)%"
    db_name: "%env(MYSQL_ENV_DB_NAME)%"

doctrine:
    dbal:
        # configure these for your database server
        # use postgresql for PostgreSQL
        # use sqlite for SQLite
        driver: 'pdo_mysql'
        server_version: '5.7'

        # only needed for MySQL
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: "mysql://%db_user%:%db_pass%@%db_host%:%db_port%/%db_name%"
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
